// This file is automatically generated. Do not modify it manually.
// For more information, see https://firebase.google.com/docs/web/learn-more#config-object
export const firebaseConfig = {
  "apiKey": "mock-api-key",
  "authDomain": "mock-auth-domain",
  "projectId": "mock-project-id",
  "storageBucket": "mock-storage-bucket",
  "messagingSenderId": "mock-messaging-sender-id",
  "appId": "mock-app-id"
};
