
"use client"

import { useEffect, useState, useRef } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { ArrowLeft, Save, Palette, Type, Image as ImageIcon, RefreshCcw, FileText } from 'lucide-react';
import useLocalStorage from '@/hooks/use-local-storage';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useToast } from '@/hooks/use-toast';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog';
import { ReportPdfHeader } from '@/components/reports/report-pdf-header';
import { Textarea } from '@/components/ui/textarea';
import type { PdfSettings } from '@/lib/types';


const availableFonts = [
  { name: 'Inter', family: "Inter, sans-serif" },
  { name: 'Roboto', family: "Roboto, sans-serif" },
  { name: 'Open Sans', family: "Open Sans, sans-serif" },
  { name: 'Lato', family: "Lato, sans-serif" },
];

const defaultSettings: PdfSettings = {
    logo: null,
    font: 'Inter',
    customFont: null,
    themeColor: '#22c55e',
    headerText: '',
    footerText: 'Generated by Ashley DRP System'
};


export default function ReportDesignerPage() {
  const { toast } = useToast();
  const [mounted, setMounted] = useState(false);
  
  const [savedPdfSettings, setSavedPdfSettings] = useLocalStorage<PdfSettings>('pdf-settings', defaultSettings);

  const [settings, setSettings] = useState(savedPdfSettings);

  const applyCustomFont = (fontDataUrl: string | null) => {
    const styleId = 'custom-pdf-font-style';
    let styleElement = document.getElementById(styleId) as HTMLStyleElement;
    if (!styleElement) {
        styleElement = document.createElement('style');
        styleElement.id = styleId;
        document.head.appendChild(styleElement);
    }
    if(fontDataUrl) {
      styleElement.innerHTML = `
        @font-face {
          font-family: 'CustomPdfFont';
          src: url(${fontDataUrl});
        }
      `;
    } else {
      styleElement.innerHTML = '';
    }
  }

  useEffect(() => {
    setMounted(true);
  }, []);

  useEffect(() => {
    if (mounted) {
      setSettings(savedPdfSettings);
      applyCustomFont(savedPdfSettings.customFont || null);
    }
  }, [mounted, savedPdfSettings]);

  const handleSettingChange = <K extends keyof PdfSettings>(key: K, value: PdfSettings[K]) => {
    setSettings(prev => ({...prev, [key]: value}));
  };

  const handleCustomFontUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const validExtensions = ['.ttf', '.otf', '.woff', '.woff2'];
      const fileExtension = '.' + file.name.split('.').pop()?.toLowerCase();
      
      if (!validExtensions.includes(fileExtension)) {
        toast({ variant: 'destructive', title: 'Invalid File Type', description: 'Please upload a .ttf, .otf, .woff, or .woff2 file.' });
        return;
      }
      const reader = new FileReader();
      reader.onload = (event) => {
        const result = event.target?.result as string;
        handleSettingChange('customFont', result);
        handleSettingChange('font', 'CustomFont');
        applyCustomFont(result);
        toast({ title: 'Custom font selected!', description: 'Click "Save Changes" to apply.' });
      };
      reader.readAsDataURL(file);
    }
  };
  
  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (loadEvent) => {
        const result = loadEvent.target?.result;
        if (typeof result === 'string') {
          handleSettingChange('logo', result);
          toast({ title: 'Logo updated!', description: 'Click "Save Changes" to apply.' });
        }
      };
      reader.readAsDataURL(file);
    }
  };

  const handleSaveChanges = () => {
    setSavedPdfSettings(settings);
    toast({ title: 'Settings saved!', description: 'Your PDF report settings have been updated.' });
  };

  const handleResetToDefault = () => {
    setSettings(defaultSettings);
    applyCustomFont(null);
    setSavedPdfSettings(defaultSettings);
    toast({ title: 'Settings Reset', description: 'All PDF report settings have been reset to their defaults.' });
  };

  if (!mounted) {
    return (
      <div className="min-h-screen bg-background text-foreground p-4 md:p-8">
        <header className="flex items-center gap-4 mb-8">
          <Button variant="outline" size="icon" asChild>
            <Link href="/"><ArrowLeft /></Link>
          </Button>
          <h1 className="text-2xl md:text-3xl font-bold">Report Designer</h1>
        </header>
        <div className="flex items-center justify-center">Loading...</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="bg-card border-b p-4">
        <div className="container mx-auto flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button variant="outline" size="icon" asChild>
              <Link href="/"><ArrowLeft /></Link>
            </Button>
            <h1 className="text-xl font-bold">Report Designer</h1>
          </div>
          <div className="ml-auto">
            <Button onClick={handleSaveChanges}>
              <Save className="mr-2 h-4 w-4" /> Save All Changes
            </Button>
          </div>
        </div>
      </header>
      <main className="p-4 md:p-6 container mx-auto">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-1 space-y-6">
                 <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2 text-lg"><FileText /> Report Content</CardTitle>
                        <CardDescription>Manage your company's logo and header/footer text.</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                        <div className='flex flex-col items-center justify-center gap-4'>
                            <div className="w-full h-24 border rounded-md flex items-center justify-center bg-muted/30">
                                {settings.logo ? (
                                    <Image src={settings.logo} alt="Current App Logo" width={120} height={60} className="object-contain" />
                                ): (
                                    <span className='text-sm text-muted-foreground'>Report Logo Preview</span>
                                )}
                            </div>
                        </div>
                        <div>
                        <Label htmlFor="logo-upload">Upload Report Logo</Label>
                        <Input id="logo-upload" type="file" accept="image/*" className="mt-2" onChange={handleImageUpload} />
                        </div>
                        <div className="space-y-2">
                          <Label htmlFor="header-text">Header Text (Optional)</Label>
                          <Input id="header-text" value={settings.headerText} onChange={(e) => handleSettingChange('headerText', e.target.value)} placeholder="e.g. Confidential Internal Document"/>
                        </div>
                        <div className="space-y-2">
                          <Label htmlFor="footer-text">Footer Text (Optional)</Label>
                          <Textarea id="footer-text" value={settings.footerText} onChange={(e) => handleSettingChange('footerText', e.target.value)} placeholder="e.g. Generated by Ashley DRP System"/>
                        </div>
                    </CardContent>
                </Card>
                 <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2 text-lg"><Palette /> Report Styling</CardTitle>
                        <CardDescription>Customize fonts and colors for your PDF reports.</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-6">
                        <div className="flex items-center justify-between">
                          <Label htmlFor="theme-color">Theme Color</Label>
                          <Input 
                            id="theme-color" 
                            type="color" 
                            value={settings.themeColor} 
                            onChange={(e) => handleSettingChange('themeColor', e.target.value)}
                            className="w-10 h-10 p-1"
                          />
                        </div>
                        <div className="flex items-center justify-between">
                            <Label htmlFor="font-select">PDF Font</Label>
                            <Select value={settings.font} onValueChange={(v) => handleSettingChange('font', v)}>
                                <SelectTrigger className="w-[180px]">
                                    <SelectValue placeholder="Select a font" />
                                </SelectTrigger>
                                <SelectContent>
                                    {availableFonts.map(f => (
                                        <SelectItem key={f.name} value={f.name}>{f.name}</SelectItem>
                                    ))}
                                    {settings.customFont && <SelectItem value="CustomFont">Custom Font</SelectItem>}
                                </SelectContent>
                            </Select>
                        </div>
                        <div>
                            <Label htmlFor="font-upload" className="text-sm font-medium">Upload Custom Font</Label>
                            <Input id="font-upload" type="file" accept=".ttf,.otf,.woff,.woff2" className="mt-2" onChange={handleCustomFontUpload} />
                            <p className="text-xs text-muted-foreground mt-2">Used for PDF generation. Replaces the default font.</p>
                        </div>
                    </CardContent>
                </Card>

                 <AlertDialog>
                    <AlertDialogTrigger asChild>
                        <Button variant="outline" className="w-full">
                            <RefreshCcw className="mr-2 h-4 w-4" /> Reset to Default
                        </Button>
                    </AlertDialogTrigger>
                    <AlertDialogContent>
                        <AlertDialogHeader>
                            <AlertDialogTitle>Reset PDF settings?</AlertDialogTitle>
                            <AlertDialogDescription>
                            This will reset all PDF report settings to their original defaults. This action cannot be undone.
                            </AlertDialogDescription>
                        </AlertDialogHeader>
                        <AlertDialogFooter>
                            <AlertDialogCancel>Cancel</AlertDialogCancel>
                            <AlertDialogAction onClick={handleResetToDefault}>Reset Settings</AlertDialogAction>
                        </AlertDialogFooter>
                    </AlertDialogContent>
                </AlertDialog>
            </div>
            <div className="lg:col-span-2">
                <Card>
                    <CardHeader>
                        <CardTitle>Live Preview</CardTitle>
                        <CardDescription>This is a preview of how your PDF report header will look.</CardDescription>
                    </CardHeader>
                    <CardContent className='bg-gray-100 p-4 rounded-b-lg'>
                        <div className="shadow-lg rounded-lg overflow-hidden">
                           <ReportPdfHeader
                                title="Example Report Title"
                                subtitle="This is an example subtitle"
                                logoSrc={settings.logo ?? null}
                                themeColor={settings.themeColor}
                                headerText={settings.headerText}
                            />
                            <div className="bg-white p-4">
                                <p className="text-sm text-gray-600" style={{fontFamily: settings.font === 'CustomFont' ? 'CustomPdfFont' : availableFonts.find(f => f.name === settings.font)?.family}}>
                                    This is body text to preview your selected font. The quick brown fox jumps over the lazy dog. 1234567890.
                                </p>
                            </div>
                             {settings.footerText && (
                                <div className="bg-white p-4 border-t text-center text-xs text-gray-500">
                                    {settings.footerText}
                                </div>
                            )}
                        </div>
                    </CardContent>
                </Card>
            </div>
        </div>
      </main>
    </div>
  )
}
