
"use client"

import { useEffect, useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { ArrowLeft, Save, Palette, RefreshCcw, FileText, Receipt, Type, User, CreditCard } from 'lucide-react';
import useLocalStorage from '@/hooks/use-local-storage';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useToast } from '@/hooks/use-toast';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog';
import { ReportPdfHeader } from '@/components/reports/report-pdf-header';
import { Textarea } from '@/components/ui/textarea';
import type { PdfSettings, AllPdfSettings, Employee, Transfer } from '@/lib/types';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { EmployeePdfCard } from '@/components/employees/employee-pdf-card';
import { TransferPdfCard } from '@/components/transmit/transfer-pdf-card';
import { formatISO } from 'date-fns';


const availableFonts = [
  { name: 'Inter', family: "Inter, sans-serif" },
  { name: 'Roboto', family: "Roboto, sans-serif" },
  { name: 'Open Sans', family: "Open Sans, sans-serif" },
  { name: 'Lato', family: "Lato, sans-serif" },
];

const defaultReportSettings: PdfSettings = {
    logo: null,
    font: 'Inter',
    customFont: null,
    themeColor: '#22c55e', // Green
    headerText: '',
    footerText: 'Generated by Ashley DRP System'
};

const defaultInvoiceSettings: PdfSettings = {
    logo: null,
    font: 'Inter',
    customFont: null,
    themeColor: '#3b82f6', // Blue
    headerText: 'Ashley DRP',
    footerText: 'Thank you for your business.'
};

const defaultCardSettings: PdfSettings = {
    logo: null,
    font: 'Inter',
    customFont: null,
    themeColor: '#8b5cf6', // Violet
    headerText: 'Employee ID',
    footerText: 'Official Company ID'
};


const defaultSettings: AllPdfSettings = {
    report: defaultReportSettings,
    invoice: defaultInvoiceSettings,
    card: defaultCardSettings,
};

// Mock data for previews
const mockEmployee: Employee = {
    id: 'preview-123',
    name: 'John Doe',
    employeeId: 'EMP-007',
    role: 'Manager',
    photoUrl: 'https://picsum.photos/seed/johndoe/400',
    email: 'john.doe@example.com',
    phone: '555-1234',
    employmentStartDate: '2022-01-15T00:00:00.000Z',
    dateOfBirth: '1985-05-20T00:00:00.000Z'
};

const mockTransfer: Transfer = {
    id: 'transfer-prev-123',
    transferDate: formatISO(new Date()),
    cargoName: "Preview Cargo to Erbil",
    destinationCity: "Erbil",
    driverName: "Driver Name",
    warehouseManagerName: "Manager Name",
    itemIds: ['item1', 'item2', 'item3']
};


export default function ReportDesignerPage() {
  const { toast } = useToast();
  const [mounted, setMounted] = useState(false);
  
  const [savedPdfSettings, setSavedPdfSettings] = useLocalStorage<AllPdfSettings>('pdf-settings', defaultSettings);

  const [settings, setSettings] = useState(savedPdfSettings);
  const [activeTab, setActiveTab] = useState<'report' | 'invoice' | 'card'>('report');

  const applyCustomFont = (fontDataUrl: string | null) => {
    const styleId = 'custom-pdf-font-style';
    let styleElement = document.getElementById(styleId) as HTMLStyleElement;
    if (!styleElement) {
        styleElement = document.createElement('style');
        styleElement.id = styleId;
        document.head.appendChild(styleElement);
    }
    if(fontDataUrl) {
      styleElement.innerHTML = `
        @font-face {
          font-family: 'CustomPdfFont';
          src: url(${fontDataUrl});
        }
      `;
    } else {
      styleElement.innerHTML = '';
    }
  }

  useEffect(() => {
    setMounted(true);
  }, []);

  useEffect(() => {
    if (mounted) {
      const updatedSettings = {
          report: savedPdfSettings.report || defaultReportSettings,
          invoice: savedPdfSettings.invoice || defaultInvoiceSettings,
          card: savedPdfSettings.card || defaultCardSettings,
      };
      setSettings(updatedSettings);
      applyCustomFont(updatedSettings[activeTab].customFont || null);
    }
  }, [mounted, savedPdfSettings, activeTab]);

  const handleSettingChange = <K extends keyof PdfSettings>(key: K, value: PdfSettings[K]) => {
    setSettings(prev => ({
        ...prev,
        [activeTab]: {
            ...prev[activeTab],
            [key]: value
        }
    }));
  };

  const handleCustomFontUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const validExtensions = ['.ttf', '.otf', '.woff', '.woff2'];
      const fileExtension = '.' + file.name.split('.').pop()?.toLowerCase();
      
      if (!validExtensions.includes(fileExtension)) {
        toast({ variant: 'destructive', title: 'Invalid File Type', description: 'Please upload a .ttf, .otf, .woff, or .woff2 file.' });
        return;
      }
      const reader = new FileReader();
      reader.onload = (event) => {
        const result = event.target?.result as string;
        handleSettingChange('customFont', result);
        handleSettingChange('font', 'CustomFont');
        applyCustomFont(result);
        toast({ title: 'Custom font selected!', description: 'Click "Save Changes" to apply.' });
      };
      reader.readAsDataURL(file);
    }
  };
  
  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (loadEvent) => {
        const result = loadEvent.target?.result;
        if (typeof result === 'string') {
          handleSettingChange('logo', result);
          toast({ title: 'Logo updated!', description: 'Click "Save Changes" to apply.' });
        }
      };
      reader.readAsDataURL(file);
    }
  };

  const handleSaveChanges = () => {
    setSavedPdfSettings(settings);
    toast({ title: 'Settings saved!', description: 'Your PDF design templates have been updated.' });
  };

  const handleResetToDefault = () => {
    setSettings(defaultSettings);
    applyCustomFont(null);
    setSavedPdfSettings(defaultSettings);
    toast({ title: 'Settings Reset', description: 'All PDF design settings have been reset to their defaults.' });
  };

  if (!mounted) {
    return (
      <div className="min-h-screen bg-background text-foreground p-4 md:p-8">
        <header className="flex items-center gap-4 mb-8">
          <Button variant="outline" size="icon" asChild>
            <Link href="/"><ArrowLeft /></Link>
          </Button>
          <h1 className="text-2xl md:text-3xl font-bold">Report Designer</h1>
        </header>
        <div className="flex items-center justify-center">Loading...</div>
      </div>
    );
  }
  
  const currentSettings = settings[activeTab];

  return (
    <div className="min-h-screen bg-background text-foreground">
      <style>{`
        @font-face {
          font-family: 'CustomPdfFont';
          src: ${currentSettings?.customFont ? `url(${currentSettings.customFont})` : 'none'};
        }
      `}</style>
      <header className="bg-card border-b p-4">
        <div className="container mx-auto flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button variant="outline" size="icon" asChild>
              <Link href="/"><ArrowLeft /></Link>
            </Button>
            <h1 className="text-xl font-bold">Report Designer</h1>
          </div>
          <div className="ml-auto flex items-center gap-4">
             <AlertDialog>
                <AlertDialogTrigger asChild>
                    <Button variant="outline">
                        <RefreshCcw className="mr-2 h-4 w-4" /> Reset All
                    </Button>
                </AlertDialogTrigger>
                <AlertDialogContent>
                    <AlertDialogHeader>
                        <AlertDialogTitle>Reset all design settings?</AlertDialogTitle>
                        <AlertDialogDescription>
                        This will reset the Report, Invoice, and Card templates to their original defaults. This action cannot be undone.
                        </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                        <AlertDialogCancel>Cancel</AlertDialogCancel>
                        <AlertDialogAction onClick={handleResetToDefault}>Reset Settings</AlertDialogAction>
                    </AlertDialogFooter>
                </AlertDialogContent>
            </AlertDialog>
            <Button onClick={handleSaveChanges}>
              <Save className="mr-2 h-4 w-4" /> Save Changes
            </Button>
          </div>
        </div>
      </header>
      <main className="p-4 md:p-6 container mx-auto">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-1 space-y-6">
                <Card>
                    <CardHeader>
                        <CardTitle>Design Template</CardTitle>
                        <CardDescription>Select which PDF type you want to customize.</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as 'report' | 'invoice' | 'card')} className="w-full">
                            <TabsList className="grid w-full grid-cols-3">
                                <TabsTrigger value="report"><FileText className="mr-2"/>Report</TabsTrigger>
                                <TabsTrigger value="invoice"><Receipt className="mr-2"/>Invoice</TabsTrigger>
                                <TabsTrigger value="card"><CreditCard className="mr-2"/>ID Card</TabsTrigger>
                            </TabsList>
                        </Tabs>
                    </CardContent>
                </Card>

                 <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2 text-lg"><FileText /> Content</CardTitle>
                        <CardDescription>Manage your company's logo and header/footer text for this template.</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                        <div>
                            <Label htmlFor="logo-upload">Company Logo</Label>
                            <Input id="logo-upload" type="file" accept="image/*" className="mt-2" onChange={handleImageUpload} />
                        </div>
                        <div className="space-y-2">
                          <Label htmlFor="header-text">Header Text (Optional)</Label>
                          <Input id="header-text" value={currentSettings.headerText} onChange={(e) => handleSettingChange('headerText', e.target.value)} placeholder="e.g. Confidential Document"/>
                        </div>
                        <div className="space-y-2">
                          <Label htmlFor="footer-text">Footer Text (Optional)</Label>
                          <Textarea id="footer-text" value={currentSettings.footerText} onChange={(e) => handleSettingChange('footerText', e.target.value)} placeholder="e.g. Generated by Ashley DRP"/>
                        </div>
                    </CardContent>
                </Card>
                 <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2 text-lg"><Palette /> Styling</CardTitle>
                        <CardDescription>Customize fonts and colors for this template.</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-6">
                        <div className="flex items-center justify-between">
                          <Label htmlFor="theme-color">Theme Color</Label>
                          <Input 
                            id="theme-color" 
                            type="color" 
                            value={currentSettings.themeColor} 
                            onChange={(e) => handleSettingChange('themeColor', e.target.value)}
                            className="w-10 h-10 p-1"
                          />
                        </div>
                        <div className="flex items-center justify-between">
                            <Label htmlFor="font-select">Font</Label>
                            <Select value={currentSettings.font} onValueChange={(v) => { handleSettingChange('font', v); if (v !== 'CustomFont') applyCustomFont(null); }}>
                                <SelectTrigger className="w-[180px]">
                                    <SelectValue placeholder="Select a font" />
                                </SelectTrigger>
                                <SelectContent>
                                    {availableFonts.map(f => (
                                        <SelectItem key={f.name} value={f.name}>{f.name}</SelectItem>
                                    ))}
                                    {currentSettings.customFont && <SelectItem value="CustomFont">Custom Font</SelectItem>}
                                </SelectContent>
                            </Select>
                        </div>
                        <div>
                            <Label htmlFor="font-upload" className="text-sm font-medium">Upload Custom Font (.ttf, .woff)</Label>
                            <Input id="font-upload" type="file" accept=".ttf,.otf,.woff,.woff2" className="mt-2" onChange={handleCustomFontUpload} />
                        </div>
                    </CardContent>
                </Card>
            </div>
            <div className="lg:col-span-2">
                <Card>
                    <CardHeader>
                        <CardTitle>Live Preview</CardTitle>
                        <CardDescription>A scaled-down A4 preview of your {activeTab} design.</CardDescription>
                    </CardHeader>
                    <CardContent className='bg-gray-100 dark:bg-gray-800/50 p-4 rounded-b-lg flex justify-center items-start'>
                        <div className="w-[595px] h-[842px] bg-white shadow-lg transform scale-[0.6] -translate-y-[160px] origin-top overflow-hidden">
                           {activeTab === 'report' && (
                                <>
                                    <ReportPdfHeader
                                        title="Example Report Title"
                                        subtitle="This is an example subtitle"
                                        logoSrc={currentSettings.logo ?? null}
                                        themeColor={currentSettings.themeColor}
                                        headerText={currentSettings.headerText}
                                    />
                                    <div className="p-6" style={{fontFamily: currentSettings.font === 'CustomFont' ? 'CustomPdfFont' : availableFonts.find(f => f.name === currentSettings.font)?.family}}>
                                        <h2 className="text-lg font-bold mb-2 text-gray-800">Sample Section</h2>
                                        <p className="text-sm text-gray-600 mb-4">
                                            This is sample body text to preview your selected font. The quick brown fox jumps over the lazy dog. 1234567890.
                                            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                                        </p>
                                        <table className="w-full text-left text-sm">
                                            <thead>
                                            <tr style={{backgroundColor: currentSettings.themeColor}} className="text-white">
                                                <th className="p-2">Item</th>
                                                <th className="p-2">Description</th>
                                                <th className="p-2 text-right">Amount</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr className='border-b'><td className="p-2">Sample A</td><td className="p-2">First item description</td><td className="p-2 text-right">1,500</td></tr>
                                            <tr className='border-b bg-gray-50'><td className="p-2">Sample B</td><td className="p-2">Second item description</td><td className="p-2 text-right">2,000</td></tr>
                                            <tr className='border-b'><td className="p-2">Sample C</td><td className="p-2">Third item description</td><td className="p-2 text-right">800</td></tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    {currentSettings.footerText && (
                                        <div className="absolute bottom-4 left-0 right-0 p-4 border-t text-center text-xs text-gray-500">
                                            {currentSettings.footerText}
                                        </div>
                                    )}
                                </>
                           )}
                           {activeTab === 'invoice' && (
                                <div className='flex justify-center items-center h-full'>
                                   <div className='transform scale-[0.8]'>
                                        <TransferPdfCard transfer={mockTransfer} totalItems={mockTransfer.itemIds.length} logoSrc={currentSettings.logo} />
                                   </div>
                               </div>
                           )}
                           {activeTab === 'card' && (
                               <div className='flex justify-center items-center h-full'>
                                   <div className='transform scale-[0.9]'>
                                        <EmployeePdfCard employee={mockEmployee} settings={currentSettings}/>
                                   </div>
                               </div>
                           )}
                        </div>
                    </CardContent>
                </Card>
            </div>
        </div>
      </main>
    </div>
  )
}
