
import { Employee, User, Role, AppSettings, AllPdfSettings, PdfSettings, ThemeColors, BranchColors, AnswerOption } from '@/lib/types';
import { adminPermissions, adminAssistantPermissions, viewerPermissions, employeePermissions, financeManagerPermissions, inventoryManagerPermissions, hrManagerPermissions } from '@/lib/permissions';
import en from '@/locales/en.json';
import ku from '@/locales/ku.json';

const defaultAnswers: [AnswerOption, AnswerOption, AnswerOption] = [
    { label: 'Excellent', value: 3 },
    { label: 'Good', value: 2 },
    { label: 'Needs Improvement', value: 1 },
];

const initialRoles: Role[] = [
    { id: 'role-admin', name: 'Admin', permissions: adminPermissions },
    { id: 'role-admin-assistant', name: 'Admin Assistant', permissions: adminAssistantPermissions },
    { id: 'role-finance-manager', name: 'Finance Manager', permissions: financeManagerPermissions },
    { id: 'role-inventory-manager', name: 'Inventory Manager', permissions: inventoryManagerPermissions },
    { id: 'role-hr-manager', name: 'HR Manager', permissions: hrManagerPermissions },
    { id: 'role-viewer', name: 'Viewer', permissions: viewerPermissions },
    { id: 'role-employee', name: 'Employee', permissions: employeePermissions },
];

const initialUsers: User[] = [
    {
        id: 'user-admin-default',
        username: 'admin',
        password: 'password',
        roleId: 'role-admin'
    },
    {
        id: 'user-darko-admin',
        username: 'Darko_admin07',
        password: '123',
        roleId: 'role-admin'
    }
];

const defaultReportColors = {
  general: '#22c55e',
  expense: '#3b82f6',
  overtime: '#f97316',
  bonus: '#8b5cf6',
  withdrawal: '#ef4444'
};

const defaultBranchColors: BranchColors = {
    Erbil: '#f97316',
    Baghdad: '#3b82f6',
    Dohuk: '#8b5cf6',
    Diwan: '#10b981',
};

const defaultReportSettings: PdfSettings = {
    logo: null,
    themeColor: '#22c55e',
    reportColors: defaultReportColors,
    tableTheme: 'striped',
    headerText: '',
    footerText: 'Generated by Ashley DRP System',
    scale: 2,
    width: 800,
    fontSize: 10,
};

const defaultInvoiceSettings: PdfSettings = {
    logo: null,
    themeColor: '#f97316',
    secondaryColor: '#0F172A',
    titleTemplate: 'Transmit to {city}',
    tableTheme: 'grid',
    headerText: 'Ashley DRP',
    footerText: 'Thank you for your business.',
    scale: 2,
    width: 800,
    fontSize: 10,
    branchColors: defaultBranchColors,
};

const defaultCardSettings: PdfSettings = {
    logo: null,
    themeColor: '#8b5cf6',
    headerText: 'Employee ID',
    footerText: 'Official Company ID',
    scale: 3,
    width: 600,
    fontSize: 12,
};

const defaultDatasheetSettings: PdfSettings = {
    logo: null,
    themeColor: '#059669',
    tableTheme: 'grid',
    headerText: 'Product Datasheet',
    footerText: 'Internal Use Only',
    scale: 2,
    width: 800,
    fontSize: 10,
};

const defaultPdfSettings: AllPdfSettings = {
    report: defaultReportSettings,
    invoice: defaultInvoiceSettings,
    card: defaultCardSettings,
    datasheet: defaultDatasheetSettings,
};

const defaultLightColors: ThemeColors = { background: '0 0% 100%', foreground: '224 71.4% 4.1%', primary: '220 82% 55%', accent: '220 13% 91%', card: '0 0% 100%', titleBar: '220 82% 55%', tabActiveBackground: '0 0% 100%', tabActiveForeground: '224 71.4% 4.1%', tableRowPrimary: '0 0% 100%', tableRowSecondary: '220 13% 96%', huanaHighlight: '210 100% 96%', locationOccupiedBorder: '210 100% 70%', locationOccupiedBg: '210 100% 96%'};
const defaultDarkColors: ThemeColors = { background: '222.2 84% 4.9%', foreground: '210 40% 98%', primary: '217.2 91.2% 59.8%', accent: '217.2 32.6% 17.5%', card: '222.2 84% 4.9%', titleBar: '217.2 91.2% 59.8%', tabActiveBackground: '222.2 84% 4.9%', tabActiveForeground: '210 40% 98%', tableRowPrimary: '222.2 84% 4.9%', tableRowSecondary: '217.2 32.6% 17.5%', huanaHighlight: '217.2 91.2% 15%', locationOccupiedBorder: '217.2 91.2% 50%', locationOccupiedBg: '217.2 91.2% 15%' };


export const initialSettings: AppSettings = {
    appLogo: 'https://scontent.fosm5-2.fna.fbcdn.net/v/t39.30808-6/359100421_1654543121624918_4357409764053776121_n.jpg?_nc_cat=111&ccb=1-7&_nc_sid=1d70fc&_nc_ohc=RRqHhfKktgwQ7kNvwGZ9wBA&_nc_oc=Adn-dOXsw6j30o0ZcGj3VZAs-bVt9v9JkUTmI2zw9OG1xr7gQCYPjQYGRSvcIQvMYgc&_nc_zt=23&_nc_ht=scontent.fosm5-2.fna&_nc_gid=_URzfjb9SusZKsrHeUvMZg&_nc_ss=8&oh=00_Afw3rq4v050pE5sZbjeVrqaa5k5g8wPxCOQ-jKJj1aSGgw&oe=69BD6DCD',
    mainBackground: 'https://i.pinimg.com/736x/7f/e9/29/7fe92929612789dec4207b9aba917d38.jpg',
    loginBackground: 'https://store.ashley.sa/cdn/shop/files/15602_63ed4394-41df-47b4-b450-eff960c05668.jpg?v=1709104619&width=1445',
    loginBackgroundVideo: null,
    loginBackgroundEmbed: 'https://www.youtube.com/embed/wJwZb9PJsNg',
    loginCardUpperImage: 'https://images2.imgix.net/p4dbimg/p20304/images/ashley-furniture-19202-55-49-amici-linen-loveseat-sofa-sectional_2.jpg?trim=color&trimtol=5&trimcolor=FFFFFF&w=1024&h=768&fm=pjpg&auto=format',
    loginButtonColor: null,
    dashboardBanner: "https://images.unsplash.com/photo-1685973323988-666a38e0acc2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    dashboardBannerHeight: 150,
    newsTickerText: 'Welcome to the Ashley DRP Manager! This is your scrolling news ticker for corporate announcements.',
    fontFamily: 'Arial',
    customFont: null,
    printHeaderImage: null,
    printFooterImage: null,
    translations: {
        en: en,
        ku: ku,
    },
    pdfSettings: defaultPdfSettings,
    lightThemeColors: defaultLightColors,
    darkThemeColors: defaultDarkColors,
    salarySettings: {
        overtimeRate: 5000,
        bonusRate: 5000,
    },
    reportHeaderColors: {
        ashleyExpenses: '#3b82f6',
        transmitCargo: '#eab308',
        placementStorage: '#22c55e',
        marketingFeedback: '#06b6d4',
        employees: '#ec4899',
    },
    dashboard: {
      fontSize: 12,
      cardRadius: 12,
      titleColor: '220 82% 55%',
      textColor: '224 71.4% 4.1%',
      accentColor: '220 13% 91%',
      textTransform: 'none',
    },
    sidebar: {
      fontSize: 12,
      textTransform: 'none',
    },
    theme: 'light',
    selectedTheme: 'default',
    language: 'en',
};


export const initialData: any = {
    employees: [
      { id: 'emp-01', name: 'Darko', employeeId: '01', role: 'Super Manager', createdAt: '2023-01-01T00:00:00.000Z', isActive: true },
    ],
    excelFiles: [],
    items: [],
    locations: [],
    expenses: [],
    expenseReports: [],
    overtime: [],
    bonuses: [],
    withdrawals: [],
    itemCategories: [
        { id: 'cat-1', name: 'Sofas' },
        { id: 'cat-2', name: 'Tables' },
        { id: 'cat-3', name: 'Chairs' },
        { id: 'cat-4', name: 'Beds' },
    ],
    transfers: [],
    transferItems: [],
    orderRequests: [],
    marketingFeedbacks: [],
    evaluationQuestions: [
        { id: 'q1', text: 'Commitment to work', answers: defaultAnswers },
        { id: 'q2', text: 'Adherence to working hours', answers: defaultAnswers },
        { id: 'q3', text: 'Acceptance of responsibility', answers: defaultAnswers },
        { id: 'q4', text: 'Initiative and offering suggestions', answers: defaultAnswers },
        { id: 'q5', text: 'Relationship with colleagues', answers: defaultAnswers },
        { id: 'q6', text: 'Appearance and personal hygiene', answers: defaultAnswers },
        { id: 'q7', text: 'Speed of completion', answers: defaultAnswers },
        { id: 'q8', text: 'Work accuracy', answers: defaultAnswers },
        { id: 'q9', text: 'Learning speed', answers: defaultAnswers },
        { id: 'q10', text: 'Problem-solving ability', answers: defaultAnswers },
        { id: 'q11', text: 'Commitment to management directives', answers: defaultAnswers },
        { id: 'q12', text: 'Ability to work under pressure', answers: defaultAnswers },
        { id: 'q13', text: 'Trustworthiness', answers: defaultAnswers },
        { id: 'q14', text: 'Customer service', answers: defaultAnswers },
        { id: 'q15', text: 'Teamwork spirit', answers: defaultAnswers },
        { id: 'q16', text: 'Continuous development', answers: defaultAnswers },
        { id: 'q17', text: 'Marketing Skills', answers: defaultAnswers },
        { id: 'q18', text: 'Sales Performance', answers: defaultAnswers },
    ],
    users: initialUsers,
    roles: initialRoles,
    soldItemsLists: [],
    activityLogs: [],
};
