
"use client"

import * as React from 'react';
import { useEffect, useState, useRef } from 'react'
import Link from 'next/link'
import Image from 'next/image'
import { ArrowLeft, Download, Upload, Save, Palette, Type, ShieldCheck, Image as ImageIcon, LayoutDashboard, RefreshCcw, Play, Newspaper, Building, FileText, Receipt, CreditCard } from 'lucide-react'
import useLocalStorage, { getAllDataForExport, importData } from '@/hooks/use-local-storage'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { useTheme } from '@/components/shared/theme-provider'
import { useToast } from '@/hooks/use-toast'
import { Input } from '@/components/ui/input'
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Slider } from '@/components/ui/slider'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog'
import { useTranslation } from '@/hooks/use-translation'
import { LanguageContext } from '@/context/language-provider'
import { ScrollArea } from '@/components/ui/scroll-area'
import { ReportPdfHeader } from '@/components/reports/report-pdf-header'
import { TransferPdfCard } from '@/components/transmit/transfer-pdf-card'
import { EmployeePdfCard } from '@/components/employees/employee-pdf-card'
import type { PdfSettings, AllPdfSettings, Employee, Transfer } from '@/lib/types';
import { format, formatISO } from 'date-fns';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { cn } from '@/lib/utils';


const availableFonts = [
  { name: 'Inter', family: "Inter, sans-serif" },
  { name: 'Roboto', family: "Roboto, sans-serif" },
  { name: 'Open Sans', family: "Open Sans, sans-serif" },
  { name: 'Lato', family: "Lato, sans-serif" },
];

const defaultReportColors = {
  general: '#22c55e',
  expense: '#3b82f6',
  overtime: '#f97316',
  bonus: '#8b5cf6',
  withdrawal: '#ef4444'
};

const defaultReportSettings: PdfSettings = {
    logo: null,
    font: 'Inter',
    customFont: null,
    themeColor: '#22c55e', // Green
    reportColors: defaultReportColors,
    tableTheme: 'striped',
    headerText: '',
    footerText: 'Generated by Ashley DRP System'
};

const defaultInvoiceSettings: PdfSettings = {
    logo: null,
    font: 'Inter',
    customFont: null,
    themeColor: '#3b82f6', // Blue
    tableTheme: 'grid',
    headerText: 'Ashley DRP',
    footerText: 'Thank you for your business.'
};

const defaultCardSettings: PdfSettings = {
    logo: null,
    font: 'Inter',
    customFont: null,
    themeColor: '#8b5cf6', // Violet
    headerText: 'Employee ID',
    footerText: 'Official Company ID'
};

const defaultPdfSettings: AllPdfSettings = {
    report: defaultReportSettings,
    invoice: defaultInvoiceSettings,
    card: defaultCardSettings,
};


// Mock data for previews
const mockEmployee: Employee = {
    id: 'preview-123',
    name: 'John Doe',
    employeeId: 'EMP-007',
    role: 'Manager',
    photoUrl: 'https://picsum.photos/seed/johndoe/400',
    email: 'john.doe@example.com',
    phone: '555-1234',
    employmentStartDate: '2022-01-15T00:00:00.000Z',
    dateOfBirth: '1985-05-20T00:00:00.000Z'
};

const mockTransfer: Transfer = {
    id: 'transfer-prev-123',
    transferDate: formatISO(new Date()),
    cargoName: "Preview Cargo to Erbil",
    destinationCity: "Erbil",
    driverName: "Driver Name",
    warehouseManagerName: "Manager Name",
    itemIds: ['item1', 'item2', 'item3']
};

const mockTransferItems = [
    { model: 'Sofa Model X', quantity: 1, notes: 'Handle with care' },
    { model: 'Dining Table', quantity: 1, notes: '' },
    { model: 'Chair Model Y', quantity: 4, notes: 'Packed separately' },
];

type ThemeColors = {
  background: string;
  foreground: string;
  primary: string;
  accent: string;
  card: string;
}

const defaultLightColors: ThemeColors = { background: '0 0% 100%', foreground: '224 71.4% 4.1%', primary: '220 82% 55%', accent: '220 13% 91%', card: '0 0% 100%' };
const defaultDarkColors: ThemeColors = { background: '222.2 84% 4.9%', foreground: '210 40% 98%', primary: '217.2 91.2% 59.8%', accent: '217.2 32.6% 17.5%', card: '222.2 84% 4.9%' };


function parseHsl(hsl: string): { h: string, s: string, l: string } {
    if (typeof hsl !== 'string' || hsl.split(' ').length !== 3) {
        const [h, s, l] = '0 0% 0%'.replace(/%/g, '').split(' ').map(s => s.trim());
        return { h, s, l };
    }
    const [h, s, l] = hsl.replace(/%/g, '').split(' ').map(s => s.trim());
    return { h, s, l };
}

function ColorPicker({ label, value, onChange }: { label: string, value: string, onChange: (value: string) => void }) {
  const { h, s, l } = parseHsl(value);

  const handleHslChange = (part: 'h' | 's' | 'l', newValue: string) => {
    const current = parseHsl(value);
    current[part] = newValue;
    onChange(`${current.h} ${current.s}% ${current.l}%`);
  };
  
  const hslToHex = (h: number, s: number, l: number): string => {
    s /= 100;
    l /= 100;
    const k = (n: number) => (n + h / 30) % 12;
    const a = s * Math.min(l, 1 - l);
    const f = (n: number) =>
      l - a * Math.max(-1, Math.min(k(n) - 3, 9 - k(n), 1));
    return `#${[0, 8, 4].map(n => Math.round(f(n) * 255).toString(16).padStart(2, '0')).join('')}`;
  }
  
  const handleHexChange = (hex: string) => {
    let r = 0, g = 0, b = 0;
    if (hex.length === 4) {
      r = parseInt(hex[1] + hex[1], 16);
      g = parseInt(hex[2] + hex[2], 16);
      b = parseInt(hex[3] + hex[3], 16);
    } else if (hex.length === 7) {
      r = parseInt(hex.substring(1, 3), 16);
      g = parseInt(hex.substring(3, 5), 16);
      b = parseInt(hex.substring(5, 7), 16);
    }
    r /= 255; g /= 255; b /= 255;
    const max = Math.max(r, g, b), min = Math.min(r, g, b);
    let hue = 0, sat = 0, light = (max + min) / 2;

    if (max !== min) {
      const d = max - min;
      sat = light > 0.5 ? d / (2 - max - min) : d / (max + min);
      switch (max) {
        case r: hue = (g - b) / d + (g < b ? 6 : 0); break;
        case g: hue = (b - r) / d + 2; break;
        case b: hue = (r - g) / d + 4; break;
      }
      hue /= 6;
    }
    hue = Math.round(hue * 360);
    sat = Math.round(sat * 100);
    light = Math.round(light * 100);
    onChange(`${hue} ${sat}% ${light}%`);
  }

  return (
    <div className="flex items-center justify-between">
      <Label className="capitalize text-sm">{label}</Label>
      <div className='flex items-center gap-2'>
        <Input 
          type="color" 
          value={hslToHex(Number(h), Number(s), Number(l))}
          onChange={(e) => handleHexChange(e.target.value)}
          className="w-8 h-8 p-1 rounded-md"
        />
        <div className="flex items-center gap-1 text-xs">
           <Input className="h-7 w-14 text-xs" placeholder="H" value={h} onChange={e => handleHslChange('h', e.target.value)} />
           <Input className="h-7 w-12 text-xs" placeholder="S" value={s} onChange={e => handleHslChange('s', e.target.value)} />
           <Input className="h-7 w-12 text-xs" placeholder="L" value={l} onChange={e => handleHslChange('l', e.target.value)} />
        </div>
      </div>
    </div>
  );
}

function ReportColorPicker({ label, value, onChange }: { label: string, value: string, onChange: (value: string) => void }) {
    return (
        <div className="flex items-center justify-between">
            <Label className="capitalize text-sm">{label}</Label>
            <Input
                type="color"
                value={value}
                onChange={(e) => onChange(e.target.value)}
                className="w-8 h-8 p-1 rounded-md"
            />
        </div>
    );
}

export default function SettingsPage() {
  const { toast } = useToast()
  const { theme, setTheme } = useTheme()
  const [mounted, setMounted] = useState(false)
  const langContext = React.useContext(LanguageContext)

  const [savedLightColors, setSavedLightColors] = useLocalStorage<ThemeColors>('light-theme-colors', defaultLightColors);
  const [savedDarkColors, setSavedDarkColors] = useLocalStorage<ThemeColors>('dark-theme-colors', defaultDarkColors);
  const [savedDashboardBanner, setSavedDashboardBanner] = useLocalStorage<string | null>('dashboard-banner', null);
  const [savedBannerHeight, setSavedBannerHeight] = useLocalStorage('dashboard-banner-height', 150);
  const [savedPdfSettings, setSavedPdfSettings] = useLocalStorage<AllPdfSettings>('pdf-settings', defaultPdfSettings);
  const [customFontBase64, setCustomFontBase64] = useLocalStorage<string | null>('custom-font-base64', null);


  const [lightColors, setLightColors] = useState(savedLightColors);
  const [darkColors, setDarkColors] = useState(savedDarkColors);
  const [dashboardBanner, setDashboardBanner] = useState(savedDashboardBanner);
  const [bannerHeight, setBannerHeight] = useState(savedBannerHeight);
  const [pdfSettings, setPdfSettings] = useState(savedPdfSettings);
  const [activePdfTab, setActivePdfTab] = useState<'report' | 'invoice' | 'card'>('report');

  const [englishTranslations, setEnglishTranslations] = useState<Record<string, string>>({});
  const [kurdishTranslations, setKurdishTranslations] = useState<Record<string, string>>({});
  
  const [importFile, setImportFile] = useState<File | null>(null);

  const importInputRef = useRef<HTMLInputElement>(null)
  
  const applyColors = (colors: ThemeColors) => {
    const root = document.documentElement;
    if (!colors) return;
    Object.entries(colors).forEach(([key, value]) => {
      if (key && value) {
        root.style.setProperty(`--${key}`, value);
      }
    });
  };
  
  const applyCustomAppFont = (fontDataUrl: string | null) => {
    const styleId = 'custom-app-font-style';
    let styleElement = document.getElementById(styleId) as HTMLStyleElement;

    if (!styleElement) {
        styleElement = document.createElement('style');
        styleElement.id = styleId;
        document.head.appendChild(styleElement);
    }

    if (fontDataUrl) {
        styleElement.innerHTML = `
            @font-face {
                font-family: 'CustomAppFont';
                src: url(${fontDataUrl});
            }
            :root {
                --font-body: 'CustomAppFont', sans-serif;
            }
        `;
    } else {
        styleElement.innerHTML = '';
        document.documentElement.style.removeProperty('--font-body');
    }
  };


  useEffect(() => {
    setMounted(true)
    if (langContext) {
      setEnglishTranslations(langContext.translations.en);
      setKurdishTranslations(langContext.translations.ku);
    }
  }, [langContext]);

  useEffect(() => {
    if (mounted) {
      setLightColors(savedLightColors);
      setDarkColors(savedDarkColors);
      setDashboardBanner(savedDashboardBanner);
      setBannerHeight(savedBannerHeight);
      const updatedPdfSettings = {
          report: { ...defaultReportSettings, ...(savedPdfSettings.report || {})},
          invoice: { ...defaultInvoiceSettings, ...(savedPdfSettings.invoice || {})},
          card: { ...defaultCardSettings, ...(savedPdfSettings.card || {})},
      };
      setPdfSettings(updatedPdfSettings);
      applyCustomAppFont(customFontBase64);
    
      if (document.documentElement.classList.contains('dark')) {
        applyColors(savedDarkColors);
      } else {
        applyColors(savedLightColors);
      }
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mounted, savedLightColors, savedDarkColors, savedDashboardBanner, savedBannerHeight, savedPdfSettings, customFontBase64])
  
  useEffect(() => {
    if(!mounted) return;
    if (theme === 'dark') {
      applyColors(darkColors);
    } else {
      applyColors(lightColors);
    }
  }, [lightColors, darkColors, theme, mounted])

  useEffect(() => {
    if(!mounted) return;
    setSavedBannerHeight(bannerHeight);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [bannerHeight]);

   const handlePdfSettingChange = <K extends keyof PdfSettings>(key: K, value: PdfSettings[K]) => {
    setPdfSettings(prev => ({
        ...prev,
        [activePdfTab]: {
            ...prev[activePdfTab],
            [key]: value
        }
    }));
  };
  
   const handleReportColorChange = (reportType: keyof NonNullable<PdfSettings['reportColors']>, color: string) => {
    setPdfSettings(prev => ({
        ...prev,
        report: {
            ...prev.report,
            reportColors: {
                ...prev.report.reportColors,
                [reportType]: color,
            }
        }
    }));
   };

  const handleCustomFontUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const validExtensions = ['.ttf', '.otf', '.woff', '.woff2'];
      const fileExtension = '.' + file.name.split('.').pop()?.toLowerCase();
      
      if (!validExtensions.includes(fileExtension)) {
        toast({ variant: 'destructive', title: 'Invalid File Type', description: 'Please upload a .ttf, .otf, .woff, or .woff2 file.' });
        return;
      }
      const reader = new FileReader();
      reader.onload = (event) => {
        const result = event.target?.result as string;
        setCustomFontBase64(result);
        applyCustomAppFont(result);
        toast({ title: 'Custom font selected!', description: 'Click "Save Changes" to apply.' });
      };
      reader.readAsDataURL(file);
    }
  };
  
  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>, setter: (value: string | null) => void, toastTitle: string) => {
    const file = e.target.files?.[0]
    if (file) {
      const reader = new FileReader()
      reader.onload = (loadEvent) => {
        const result = loadEvent.target?.result
        if (typeof result === 'string') {
          setter(result)
          toast({ title: toastTitle, description: 'Click "Save Changes" to apply.' })
        }
      }
      reader.readAsDataURL(file)
    }
  }

  const handleSaveChanges = () => {
    setSavedLightColors(lightColors);
    setSavedDarkColors(darkColors);
    setSavedDashboardBanner(dashboardBanner);
    setSavedBannerHeight(bannerHeight);
    setSavedPdfSettings(pdfSettings);
    setCustomFontBase64(customFontBase64);

    if(langContext) {
      langContext.setTranslations(englishTranslations, 'en');
      langContext.setTranslations(kurdishTranslations, 'ku');
    }
    toast({ title: 'Settings saved!', description: 'Your appearance and language settings have been updated.' });
  }

  const handleResetToDefault = () => {
    setLightColors(defaultLightColors);
    setDarkColors(defaultDarkColors);
    setDashboardBanner(null);
    setBannerHeight(150);
    setPdfSettings(defaultPdfSettings);
    setCustomFontBase64(null);
    applyCustomAppFont(null);
    
    setSavedLightColors(defaultLightColors);
    setSavedDarkColors(defaultDarkColors);
    setSavedDashboardBanner(null);
    setSavedBannerHeight(150);
    setSavedPdfSettings(defaultPdfSettings);
    setCustomFontBase64(null);
    
    if (langContext) {
        langContext.resetTranslations();
    }
    
    toast({ title: 'Settings Reset', description: 'All settings have been reset to their default values.' });
  }
  
  const handleExport = async () => {
    try {
        const data = await getAllDataForExport();
        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `ashley-hr-backup-${new Date().toISOString().split('T')[0]}.json`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        toast({ title: 'Data exported successfully!' });

    } catch (error) {
        console.error("Export failed:", error);
        toast({ variant: 'destructive', title: 'Export failed', description: 'Could not export all application data.' });
    }
  }

  const handleImportFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      setImportFile(file);
    }
  };

  const handleRunImport = () => {
    if (importFile) {
      const reader = new FileReader();
      reader.onload = async (event) => {
        try {
          const backupData = JSON.parse(event.target?.result as string);
          await importData(backupData);

          toast({ title: 'Data imported successfully!', description: 'The page will now reload to apply changes.' });
          setTimeout(() => window.location.reload(), 2000);

        } catch (error) {
          console.error("Import failed:", error);
          toast({ variant: 'destructive', title: 'Import failed', description: 'Invalid or corrupted file.' });
        } finally {
            setImportFile(null);
            if(importInputRef.current) importInputRef.current.value = "";
        }
      };
      reader.readAsText(importFile);
    }
  };


  if (!mounted) {
    return (
        <div className="min-h-screen bg-background text-foreground p-4 md:p-8">
            <header className="flex items-center gap-4 mb-8">
                <Button variant="outline" size="icon" asChild>
                    <Link href="/"> <ArrowLeft /> </Link>
                </Button>
                <h1 className="text-2xl md:text-3xl font-bold">Settings</h1>
            </header>
            <div className="flex items-center justify-center">Loading...</div>
        </div>
    );
  }

  const currentPdfSettings = pdfSettings[activePdfTab];

  return (
    <div className="min-h-screen bg-background text-foreground">
        <style>{`
            @font-face {
              font-family: 'CustomPdfFont';
              src: ${currentPdfSettings?.customFont ? `url(${currentPdfSettings.customFont})` : 'none'};
            }
        `}</style>
      <header className="bg-card border-b p-4">
        <div className="container mx-auto flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button variant="outline" size="icon" asChild>
              <Link href="/"> <ArrowLeft /> </Link>
            </Button>
            <h1 className="text-xl font-bold">Settings</h1>
          </div>
          <div className="ml-auto flex items-center gap-4">
             <AlertDialog>
                <AlertDialogTrigger asChild>
                    <Button variant="outline">
                        <RefreshCcw className="mr-2 h-4 w-4" /> Reset All
                    </Button>
                </AlertDialogTrigger>
                <AlertDialogContent>
                    <AlertDialogHeader>
                        <AlertDialogTitle>Reset all settings?</AlertDialogTitle>
                        <AlertDialogDescription>
                        This will reset all appearance, language, and PDF settings to their original defaults. Your data will not be affected. This action cannot be undone.
                        </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                        <AlertDialogCancel>Cancel</AlertDialogCancel>
                        <AlertDialogAction onClick={handleResetToDefault}>Reset Settings</AlertDialogAction>
                    </AlertDialogFooter>
                </AlertDialogContent>
            </AlertDialog>
            <Button onClick={handleSaveChanges}>
              <Save className="mr-2 h-4 w-4" /> Save All Changes
            </Button>
          </div>
        </div>
      </header>
      <main className="p-4 md:p-6 container mx-auto">
        <Tabs defaultValue="design" className="w-full">
            <TabsList className="grid w-full grid-cols-4">
                <TabsTrigger value="design">Design</TabsTrigger>
                <TabsTrigger value="language">Language</TabsTrigger>
                <TabsTrigger value="pdf">PDF & Reports</TabsTrigger>
                <TabsTrigger value="data">Data Management</TabsTrigger>
            </TabsList>

            <TabsContent value="design" className="pt-6">
                <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-6">
                    <Card>
                        <CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Palette /> General</CardTitle></CardHeader>
                        <CardContent className="space-y-6">
                            <div className="flex items-center justify-between">
                                <Label htmlFor="dark-mode">Dark Mode</Label>
                                <Switch id="dark-mode" checked={theme === 'dark'} onCheckedChange={() => setTheme(theme === 'light' ? 'dark' : 'light')} />
                            </div>
                             <div>
                                <Label htmlFor="font-upload" className="text-sm font-medium">Upload Custom App Font (.ttf, .woff)</Label>
                                <Input id="font-upload" type="file" accept=".ttf,.otf,.woff,.woff2" className="mt-2" onChange={handleCustomFontUpload} />
                            </div>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardHeader><CardTitle className="flex items-center gap-2 text-lg"><LayoutDashboard /> Dashboard</CardTitle></CardHeader>
                        <CardContent className="space-y-6">
                            <div className="w-full h-24 border rounded-md flex items-center justify-center bg-muted/30 relative overflow-hidden">
                                {dashboardBanner ? <Image src={dashboardBanner} alt="Current Dashboard Banner" fill={true} className="object-cover" /> : <span className='text-sm text-muted-foreground'>Dashboard Banner Preview</span>}
                            </div>
                            <div>
                                <Label htmlFor="banner-upload">Upload Dashboard Banner</Label>
                                <Input id="banner-upload" type="file" accept="image/*" className="mt-2" onChange={(e) => handleImageUpload(e, setDashboardBanner, "Banner updated!")} />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="banner-height">Banner Height: {bannerHeight}px</Label>
                                <Slider id="banner-height" min={80} max={300} step={10} value={[bannerHeight]} onValueChange={(value) => setBannerHeight(value[0])} />
                            </div>
                        </CardContent>
                    </Card>
                    <Card className="lg:col-span-2 xl:col-span-1">
                        <CardHeader><CardTitle className="flex items-center gap-2"><Palette/> Color Palette</CardTitle><CardDescription>Adjust colors for light and dark themes.</CardDescription></CardHeader>
                        <CardContent>
                            <Tabs defaultValue="light" className="w-full">
                                <TabsList className="grid w-full grid-cols-2">
                                    <TabsTrigger value="light">Light Mode</TabsTrigger>
                                    <TabsTrigger value="dark">Dark Mode</TabsTrigger>
                                </TabsList>
                                <TabsContent value="light" className="space-y-4 pt-4">
                                    <ColorPicker label="Background" value={lightColors.background} onChange={(c) => setLightColors(p => ({...p, background: c}))} />
                                    <ColorPicker label="Foreground" value={lightColors.foreground} onChange={(c) => setLightColors(p => ({...p, foreground: c}))} />
                                    <ColorPicker label="Primary" value={lightColors.primary} onChange={(c) => setLightColors(p => ({...p, primary: c}))} />
                                    <ColorPicker label="Accent" value={lightColors.accent} onChange={(c) => setLightColors(p => ({...p, accent: c}))} />
                                    <ColorPicker label="Card" value={lightColors.card} onChange={(c) => setLightColors(p => ({...p, card: c}))} />
                                </TabsContent>
                                    <TabsContent value="dark" className="space-y-4 pt-4">
                                    <ColorPicker label="Background" value={darkColors.background} onChange={(c) => setDarkColors(p => ({...p, background: c}))} />
                                    <ColorPicker label="Foreground" value={darkColors.foreground} onChange={(c) => setDarkColors(p => ({...p, foreground: c}))} />
                                    <ColorPicker label="Primary" value={darkColors.primary} onChange={(c) => setDarkColors(p => ({...p, primary: c}))} />
                                    <ColorPicker label="Accent" value={darkColors.accent} onChange={(c) => setDarkColors(p => ({...p, accent: c}))} />
                                    <ColorPicker label="Card" value={darkColors.card} onChange={(c) => setDarkColors(p => ({...p, card: c}))} />
                                </TabsContent>
                            </Tabs>
                        </CardContent>
                    </Card>
                </div>
            </TabsContent>

            <TabsContent value="language" className="pt-6">
                 <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2">Language & Translations</CardTitle>
                        <CardDescription>Edit the text for different languages used in the app.</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <Tabs defaultValue="english">
                            <TabsList>
                                <TabsTrigger value="english">English</TabsTrigger>
                                <TabsTrigger value="kurdish">Kurdish (کوردی)</TabsTrigger>
                            </TabsList>
                            <TabsContent value="english">
                                <ScrollArea className="h-96 pr-4">
                                    <div className="space-y-4">
                                        {Object.entries(englishTranslations).map(([key, value]) => (
                                            <div key={key} className="grid grid-cols-3 gap-4 items-center">
                                                <Label htmlFor={`en-${key}`} className="text-muted-foreground break-all">{key}</Label>
                                                <Input id={`en-${key}`} value={value} onChange={e => setEnglishTranslations(prev => ({ ...prev, [key]: e.target.value }))} className="col-span-2" />
                                            </div>
                                        ))}
                                    </div>
                                </ScrollArea>
                            </TabsContent>
                            <TabsContent value="kurdish">
                                <ScrollArea className="h-96 pr-4">
                                    <div className="space-y-4" dir='rtl'>
                                        {Object.entries(kurdishTranslations).map(([key, value]) => (
                                            <div key={key} className="grid grid-cols-3 gap-4 items-center">
                                                <Label htmlFor={`ku-${key}`} className="text-muted-foreground break-all">{key}</Label>
                                                <Input id={`ku-${key}`} value={value} onChange={e => setKurdishTranslations(prev => ({ ...prev, [key]: e.target.value }))} className="col-span-2" dir='rtl' />
                                            </div>
                                        ))}
                                    </div>
                                </ScrollArea>
                            </TabsContent>
                        </Tabs>
                    </CardContent>
                </Card>
            </TabsContent>

            <TabsContent value="pdf" className="pt-6">
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                    <div className="lg:col-span-1 space-y-6">
                        <Card>
                            <CardHeader>
                                <CardTitle>PDF Template</CardTitle>
                                <CardDescription>Select which PDF type you want to customize.</CardDescription>
                            </CardHeader>
                            <CardContent>
                                <Tabs value={activePdfTab} onValueChange={(v) => setActivePdfTab(v as 'report' | 'invoice' | 'card')} className="w-full">
                                    <TabsList className="grid w-full grid-cols-3">
                                        <TabsTrigger value="report"><FileText className="mr-2"/>Report</TabsTrigger>
                                        <TabsTrigger value="invoice"><Receipt className="mr-2"/>Invoice</TabsTrigger>
                                        <TabsTrigger value="card"><CreditCard className="mr-2"/>ID Card</TabsTrigger>
                                    </TabsList>
                                </Tabs>
                            </CardContent>
                        </Card>
                        <Card>
                            <CardHeader>
                                <CardTitle className="flex items-center gap-2 text-lg"><FileText /> Content</CardTitle>
                            </CardHeader>
                            <CardContent className="space-y-4">
                                <div>
                                    <Label htmlFor="logo-upload">Company Logo</Label>
                                    <Input id="logo-upload" type="file" accept="image/*" className="mt-2" onChange={(e) => handleImageUpload(e, (val) => handlePdfSettingChange('logo', val), "Logo updated!")} />
                                </div>
                                <div className="space-y-2">
                                <Label htmlFor="header-text">Header Text (Optional)</Label>
                                <Input id="header-text" value={currentPdfSettings.headerText} onChange={(e) => handlePdfSettingChange('headerText', e.target.value)} placeholder="e.g. Confidential Document"/>
                                </div>
                                <div className="space-y-2">
                                <Label htmlFor="footer-text">Footer Text (Optional)</Label>
                                <Input id="footer-text" value={currentPdfSettings.footerText} onChange={(e) => handlePdfSettingChange('footerText', e.target.value)} placeholder="e.g. Generated by Ashley DRP"/>
                                </div>
                            </CardContent>
                        </Card>
                         <Card>
                            <CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Palette /> Styling</CardTitle></CardHeader>
                            <CardContent className="space-y-6">
                                {activePdfTab === 'report' && (
                                    <div className="space-y-4">
                                        <CardDescription>Set a unique color for each report type's header.</CardDescription>
                                        <ReportColorPicker label="General" value={pdfSettings.report.reportColors?.general || '#000000'} onChange={(c) => handleReportColorChange('general', c)} />
                                        <ReportColorPicker label="Expense" value={pdfSettings.report.reportColors?.expense || '#000000'} onChange={(c) => handleReportColorChange('expense', c)} />
                                        <ReportColorPicker label="Overtime" value={pdfSettings.report.reportColors?.overtime || '#000000'} onChange={(c) => handleReportColorChange('overtime', c)} />
                                        <ReportColorPicker label="Bonus" value={pdfSettings.report.reportColors?.bonus || '#000000'} onChange={(c) => handleReportColorChange('bonus', c)} />
                                        <ReportColorPicker label="Withdrawal" value={pdfSettings.report.reportColors?.withdrawal || '#000000'} onChange={(c) => handleReportColorChange('withdrawal', c)} />
                                    </div>
                                )}
                                {(activePdfTab === 'invoice' || activePdfTab === 'card') && (
                                    <div className="flex items-center justify-between">
                                        <Label htmlFor="theme-color">Theme Color</Label>
                                        <Input id="theme-color" type="color" value={currentPdfSettings.themeColor} onChange={(e) => handlePdfSettingChange('themeColor', e.target.value)} className="w-10 h-10 p-1" />
                                    </div>
                                )}
                                {(activePdfTab === 'report' || activePdfTab === 'invoice') && (
                                    <div className="flex items-center justify-between">
                                        <Label htmlFor="table-theme-select">Table Theme</Label>
                                        <Select value={currentPdfSettings.tableTheme} onValueChange={(v: 'striped' | 'grid') => handlePdfSettingChange('tableTheme', v)}>
                                            <SelectTrigger className="w-[180px]"><SelectValue /></SelectTrigger>
                                            <SelectContent>
                                                <SelectItem value="striped">Striped</SelectItem>
                                                <SelectItem value="grid">Grid</SelectItem>
                                            </SelectContent>
                                        </Select>
                                    </div>
                                )}
                            </CardContent>
                        </Card>
                    </div>
                    <div className="lg:col-span-2">
                        <Card>
                            <CardHeader><CardTitle>Live Preview</CardTitle><CardDescription>A preview of your {activePdfTab} design.</CardDescription></CardHeader>
                            <CardContent className='bg-muted/50 p-6 rounded-b-lg flex justify-center items-start overflow-auto'>
                                <div className="w-[595px] min-h-[842px] bg-white shadow-lg transform scale-[0.6] origin-top overflow-hidden flex flex-col">
                                {activePdfTab === 'report' && (
                                    <>
                                        <ReportPdfHeader title="Example Report Title" subtitle="This is an example subtitle" logoSrc={currentPdfSettings.logo ?? null} themeColor={pdfSettings.report.reportColors?.general} headerText={currentPdfSettings.headerText} />
                                        <div className="p-6" style={{fontFamily: availableFonts.find(f => f.name === currentPdfSettings.font)?.family}}>
                                            <p className="text-sm text-gray-600 mb-4">This is sample body text. The quick brown fox jumps over the lazy dog.</p>
                                        </div>
                                        {currentPdfSettings.footerText && <div className="mt-auto p-4 border-t text-center text-xs text-gray-500">{currentPdfSettings.footerText}</div>}
                                    </>
                                )}
                                {activePdfTab === 'invoice' && (
                                    <div className="flex flex-col h-full text-black">
                                        <div className="p-1">
                                            <TransferPdfCard
                                                transfer={mockTransfer}
                                                logoSrc={currentPdfSettings.logo}
                                                totalItems={mockTransfer.itemIds.length}
                                            />
                                        </div>
                                        <div className='p-6 flex-grow' style={{fontFamily: availableFonts.find(f => f.name === currentPdfSettings.font)?.family}}>
                                            <Table className={cn(currentPdfSettings.tableTheme === 'grid' && 'border')}>
                                                <TableHeader>
                                                    <TableRow style={{backgroundColor: currentPdfSettings.themeColor}} className="hover:bg-primary/90">
                                                        <TableHead className="text-white">Model</TableHead>
                                                        <TableHead className="text-white">Quantity</TableHead>
                                                        <TableHead className="text-white">Notes</TableHead>
                                                    </TableRow>
                                                </TableHeader>
                                                <TableBody>
                                                    {mockTransferItems.map((item, index) => (
                                                        <TableRow key={index} className={cn(currentPdfSettings.tableTheme === 'striped' && 'odd:bg-muted/50')}>
                                                            <TableCell>{item.model}</TableCell>
                                                            <TableCell>{item.quantity}</TableCell>
                                                            <TableCell>{item.notes}</TableCell>
                                                        </TableRow>
                                                    ))}
                                                </TableBody>
                                            </Table>
                                        </div>
                                    </div>
                                )}
                                {activePdfTab === 'card' && <div className='flex justify-center items-center h-full'><EmployeePdfCard employee={mockEmployee} settings={currentPdfSettings}/></div>}
                                </div>
                            </CardContent>
                        </Card>
                    </div>
                </div>
            </TabsContent>
            
            <TabsContent value="data" className="pt-6">
                 <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2 text-lg"><ShieldCheck /> Data Management</CardTitle>
                        <CardDescription>Backup or restore all application data. Your data is stored in the browser, so be sure to make regular backups.</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                        <div className="p-4 border rounded-lg flex flex-col sm:flex-row items-center justify-between gap-4">
                            <p className="font-medium">Export all application data</p>
                            <Button onClick={handleExport} variant="outline"><Download className="mr-2 h-4 w-4" /> Export Data</Button>
                        </div>
                        <div className="p-4 border rounded-lg space-y-4">
                            <p className="font-medium">Import data from a backup file</p>
                            <p className="text-sm text-destructive">Warning: Importing data will overwrite all existing data in the application. This action cannot be undone.</p>
                            <div className="flex flex-col sm:flex-row items-center gap-4">
                                <Input type="file" ref={importInputRef} className="max-w-xs" accept=".json" onChange={handleImportFileSelect} />
                                <Button onClick={handleRunImport} disabled={!importFile}><Play className="mr-2 h-4 w-4" /> Run Import</Button>
                            </div>
                        </div>
                    </CardContent>
                </Card>
            </TabsContent>
        </Tabs>
      </main>
    </div>
  )
}
